// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSRPwNR1v0c4RcG4KyLzXPXpJsSFapCkE',
    appId: '1:905829550186:web:a90f921fdc9c75af3b6213',
    messagingSenderId: '905829550186',
    projectId: 'answeralyzer-2',
    authDomain: 'answeralyzer-2.firebaseapp.com',
    storageBucket: 'answeralyzer-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMTd4Ltv1oe3Db_bpOIWH0fEs5VuJuBZA',
    appId: '1:905829550186:android:02972fa8e5b9a7283b6213',
    messagingSenderId: '905829550186',
    projectId: 'answeralyzer-2',
    storageBucket: 'answeralyzer-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKRYG8STlAgs_OvQUIrNo7ctZEHNEHRSI',
    appId: '1:905829550186:ios:e619cf6462d3c6783b6213',
    messagingSenderId: '905829550186',
    projectId: 'answeralyzer-2',
    storageBucket: 'answeralyzer-2.appspot.com',
    iosClientId: '905829550186-cfqtbbes9k04f66ks5b7kspee2o9j18q.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotProject',
  );
}
